### ISSUE TITLE
gradle构建时出现如下retrolambda错误，是什么原因？

### ISSUE THREAD

**Issue by baibig** [drakeet/Meizhi#11]
* What went wrong:
Execution failed for task ':app:compileRetrolambdaGooglePlayDebug'.
> Could not resolve all dependencies for configuration ':app:retrolambdaConfig'.
   > Could not resolve net.orfjackal.retrolambda:retrolambda:2.0.3.
     Required by:
         Meizhi:app:unspecified
      > No cached version of net.orfjackal.retrolambda:retrolambda:2.0.3 available for offline mode.
      > No cached version of net.orfjackal.retrolambda:retrolambda:2.0.3 available for offline mode.
      > No cached version of net.orfjackal.retrolambda:retrolambda:2.0.3 available for offline mode.

**Comment by drakeet** [comment]
看英文啊。。你是离线模式。。。

Huang Jian <notifications@github.com>于2015年9月5日周六 14:46写道：

**Comment by baibig** [comment]
看了，之前只改了gradle的设置，没改compiler的配置，现已解决。谢谢。

**Comment by zhangkehu** [comment]
然而也不说怎么解决的啊？

**Comment by cuijianzhi** [comment]
然而也不说怎么解决的啊？

**Comment by drakeet** [comment]
@zhangkehu 针对这个 issue 关闭离线模式即可

**Comment by cuijianzhi** [comment]
检测一下设置中compiler command-line Options：
看时候加了--offline
