### ISSUE TITLE
下拉刷新时的crash

### ISSUE THREAD

**Issue by wrjqss** [drakeet/Meizhi#23]
下拉刷新刚触发，迅速上滑。。崩

**Comment by drakeet** [comment]
额，我想起这个问题了，最近改的代码又导致这个问题，感谢反馈！

壱级天災 <notifications@github.com>于2015年10月16日周五 20:28写道：

**Comment by drakeet** [comment]
已经修复：https://github.com/drakeet/Meizhi/commit/667527224f52a3f336266eb7f6a456fce9e3a5c7
