### ISSUE TITLE
关于避免下拉刷新 crash

### ISSUE THREAD

**Issue by laowch** [drakeet/Meizhi#24]
看了下代码，Crash 的原因是在 requestDataRefresh() 方法中对 mMeizhiList 进行了 clear()，并且没有 notify RV 数据发生了变化。

这并不是 RV 的 bug，而是对 RV 的误用。

感觉没有必要在 requestDataRefresh() 进行 clear，因为这时候新数据还没有来，仍然需要展示旧数据。

这样就不需要对 Touch 事件进行拦截了。

**Comment by drakeet** [comment]
我知道是这个原因……那你来解决……

laowch <notifications@github.com>于2015年10月20日周二 11:48写道：

**Comment by drakeet** [comment]
就算移动 clear 到任何位置都是同样可能触发这个问题的，除非我的解决方案……所以，你如果有好办法，你帮忙解决下吧，非常感谢！

许晓锋 <drakeet.me@gmail.com>于2015年10月20日周二 11:55写道：

**Comment by laowch** [comment]
我不太确定你的需求是什么

照我的想法，直接去掉 requestDataRefresh() 方法中的 clear 就好了。

因为你已经在 loadData 的回调中，进行了 clear （此处因为会 notify，所以不会触发这个问题）
```
                    if (clean) {
                        mMeizhiList.clear();
                    }
                    mMeizhiList.addAll(meizhis);
                    mMeizhiListAdapter.notifyDataSetChanged();
```

**Comment by drakeet** [comment]
额，你提醒了我，貌似我之前尝试这么解决过，我再试试

**Comment by drakeet** [comment]
谢谢你，应该是可以了，但理论上其实这样也是可能触发这个异常的，只是触发机率十分小，即在 mMeizhiList.clear() 之后 notifyDataSetChanged 之前的瞬间，有可能同样触发。

**Comment by laowch** [comment]
并不会，因为这是在 UI 线程中执行的，和滚动是同一个线程，所以那个瞬间是无法滚动的 ：）

**Comment by drakeet** [comment]
哦！是的！谢谢指教！

laowch <notifications@github.com>于2015年10月20日周二 12:50写道：
