### ISSUE TITLE
会不会将retrofit切换成2.0？

### ISSUE THREAD

**Issue by hcjcch** [drakeet/Meizhi#26]

**Comment by drakeet** [comment]
会，但 2.0 目前有些 bug，等正式版。

huangchen <notifications@github.com>于2015年11月9日周一 00:11写道：

**Comment by hcjcch** [comment]
retrofit已经2.0了哦

**Comment by drakeet** [comment]
会，这几天就更新。

huangchen <notifications@github.com>于2016年3月17日周四 00:03写道：
