### ISSUE TITLE
关于Rxandroid的一个问题

### ISSUE THREAD

**Issue by ervinsae** [drakeet/Meizhi#35]
private void loadData(boolean clean) {
        .map(meizhiData -> meizhiData.results)//map转换类型操作符，将返回的MeiZhiData类型的数据转成List<Meizhi>类型
        .flatMap(Observable::from)//flatmap输出一个一对多的数据，它输出的Observable对象才是Subcribe所真正想接收的数据,这里变形为：Observable.from(List<Meizhi>)，观察者将接收到一个个Meizhi对象。
       ……
         .subscribe(meizhis -> { //为什么这里接收的是List<Meizhi>而不是Meizhi对象
                   if (clean) mMeizhiList.clear();
                   mMeizhiList.addAll(meizhis);
                   mMeizhiListAdapter.notifyDataSetChanged();
                   setRequestDataRefresh(false);
               }, throwable -> loadError(throwable));
    }

这里注释是我自己对Rxandroid的理解，问题是：为什么最后subcribler接收到的是一个List<Meizhi>而不是一个个Meizhi对象，因为flatMap中用了observable.from()啊！

刚刚学习RxJava好多东西还不太清楚，希望得到大神的回答。多谢！

**Comment by lowwor** [comment]
注意toSortedList()操作符！

**Comment by ervinsae** [comment]
toSortedList()操作符，这个只是对list中meizhi对象根据publishedAt字段进行排序啊。

**Comment by lowwor** [comment]
直接看javadoc就知道了。
*toSortedList()*
Returns an Observable that emits a list that contains the items emitted by the source Observable, in a sorted order.
![toSortedList()](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/toSortedList.png)

**Comment by ervinsae** [comment]
哇，多谢！终于理顺了！
