### ISSUE TITLE
必须要java8才能build吗？

### ISSUE THREAD

**Issue by TonyChiangUSA** [drakeet/Meizhi#36]
Error:Execution failed for task ':app:compileGooglePlayDebugJavaWithJavac'.
> When running gradle with java 5, 6 or 7, you must set the path to jdk8, either with property retrolambda.jdk or environment variable JAVA8_HOME

**Comment by drakeet** [comment]
是

Tony Chiang <notifications@github.com>于2016年1月20日周三 15:07写道：

**Comment by zhushi91** [comment]
我换成jdk8了为什么还是不行  java version "1.8.0_60"
