### ISSUE TITLE
在没有网络的情况下打开应用，就会自动退出，就是这么设计的么？

### ISSUE THREAD

**Issue by snowjade** [drakeet/Meizhi#39]

**Comment by drakeet** [comment]
没有，最近API改了，估计引起问题了，我看看，感谢反馈！

snowjade <notifications@github.com>于2016年3月1日周二 17:39写道：

**Comment by drakeet** [comment]
v2.6.0
* 适配新的API服务
* 修复没有网络的时候导致异常问题
