### ISSUE TITLE
我把jdk换成8了还是有这个问题

### ISSUE THREAD

**Issue by zhushi91** [drakeet/Meizhi#41]
Error:Execution failed for task ':app:compileGooglePlayDebugJavaWithJavac'.
> When running gradle with java 5, 6 or 7, you must set the path to jdk8, either with property retrolambda.jdk or environment variable JAVA8_HOME

**Comment by foobean** [comment]
好奇怪，我也有这个问题，楼主能回答一下吗，还有要必须用jdk8吗

**Comment by SharerMax** [comment]
你环境变量怎么配的？看日志你Java8的环境常量名师JAVA8_HOME，而不是Java_home

foobean <notifications@github.com>于2016年3月25日周五 10:57写道：

**Comment by zhushi91** [comment]
我的环境变量名改为JAVA8_HOME还是出现一样的问题

**Comment by astrogypsophila** [comment]
--open module settings
  --SDK Location 
    --JDK Location (u can try new version)
