### ISSUE TITLE
为什么不用okhttp cache，而用db?

### ISSUE THREAD

**Issue by ihrthk** [drakeet/Meizhi#44]

**Comment by drakeet** [comment]
我不清楚 okhttp cache 能做到我想要的。但话说回来，为什么要用 okhttp cache 而不用 db？

zhangls <notifications@github.com>于2016年5月5日周四 10:37写道：

**Comment by 416679828** [comment]
为什么要用db而不用cache

**Comment by ihrthk** [comment]
个人认为，应该使用okhttp cache
1.更加符合rest ful规范，这样也使用请求头和响应头，来制定缓存策略
2.file cache要比db有更快的读取速度(虽然修改麻烦点，但是移动端最主要是浏览)
3.不需要再自己写缓存逻辑，减少开发和维护工作量

**Comment by drakeet** [comment]
谢谢！但这个项目没有人在持续开发了，所以我不得不关闭这个 issue，除非你能提交一个清晰的 PR.
