### ISSUE TITLE
貌似崩了

### ISSUE THREAD

**Issue by fangcheng0724** [drakeet/Meizhi#45]
刷新不了

**Comment by drakeet** [comment]
应该是 API 改了，我待会儿看看
方程 <notifications@github.com>于2016年6月19日 周日01:21写道：

**Comment by drakeet** [comment]
我试了下，一切正常，你看下你是不是 2.6.0 版本，如果是的话，你可以下载源代码进行 debug 看看哪里出问题了，并欢迎提交 pull request :)

<img src="https://cloud.githubusercontent.com/assets/5214214/16177828/6837190a-366a-11e6-8421-91bae413e243.png" width=256 height=449/>
