### ISSUE TITLE
这个baseactivity里的CompositeSubscription 

### ISSUE THREAD

**Issue by chaozaiai** [drakeet/Meizhi#48]
baseactivity里的CompositeSubscription 也不是每一个activity你都用到了呀，没有更好的写法吗？

**Comment by drakeet** [comment]
有的，使用 delegate 或 helper 组合替代继承
chaozaiai <notifications@github.com>于2016年7月5日 周二16:52写道：

**Comment by yogkin** [comment]
弱弱的问一下：：编译的时候出现，DisposalException: 'gson-2.3.1' already disposed，没找到关联gson的代码。。。
