### ISSUE TITLE
DisposalException: 'gson-2.3.1' already disposed

### ISSUE THREAD

**Issue by yogkin** [drakeet/Meizhi#49]
弱弱的问一下：：编译的时候出现，DisposalException: 'gson-2.3.1' already disposed，没找到关联gson的代码。。。

**Comment by drakeet** [comment]
gson convertor
yogkin <notifications@github.com>于2016年7月11日 周一12:27写道：

**Comment by yogkin** [comment]
我重新打开项目可以运行了，我在dependencies和lib目录里面找不到引入gson的代码，能简单说明一下在什么位置引入这个库的么？ths

**Comment by drakeet** [comment]
你可以自己引入某个具体的 gson 版本，gradle 能够自动判定最新版本并选择使用最新版本
