### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by yogkin** [drakeet/Meizhi#50]
当我运行这个项目的时候提示500错误

07-11 14:07:54.536 3534-3534/me.drakeet.meizhi W/System.err: retrofit.RetrofitError: 500 Internal Server Error
07-11 14:07:54.536 3534-3534/me.drakeet.meizhi W/System.err:     at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
07-11 14:07:54.536 3534-3534/me.drakeet.meizhi W/System.err:     at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
07-11 14:07:54.536 3534-3534/me.drakeet.meizhi W/System.err:     at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
07-11 14:07:54.536 3534-3534/me.drakeet.meizhi W/System.err:     at retrofit.RxSupport$2.run(RxSupport.java:55)
07-11 14:07:54.536 3534-3534/me.drakeet.meizhi W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
07-11 14:07:54.536 3534-3534/me.drakeet.meizhi W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
07-11 14:07:54.536 3534-3534/me.drakeet.meizhi W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
07-11 14:07:54.536 3534-3534/me.drakeet.meizhi W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
07-11 14:07:54.536 3534-3534/me.drakeet.meizhi W/System.err:     at retrofit.Platform$Android$2$1.run(Platform.java:142)
07-11 14:07:54.536 3534-3534/me.drakeet.meizhi W/System.err:     at java.lang.Thread.run(Thread.java:841)

**Comment by drakeet** [comment]
我这边无法复现，如果你发现问题，可以查看下原因并尝试解决 : )

**Comment by daimajia** [comment]
看下是哪个接口出的问题？ 服务器有时候压力大的时候会宕机，会出现这个问题。

跟 Android 代码没有关系。
