### ISSUE TITLE
VideoImageView 的预览功能无效？

### ISSUE THREAD

**Issue by hhaAndroid** [drakeet/Meizhi#51]
在我的手机上预览功能没有用，不知道啥原因？我的是Android 6.0

**Comment by drakeet** [comment]
原因是因为它的预览图之前是我在我的服务器手动添加的，后来懒了，不再手动更新匹配的预览图。所以之后可能考虑将这个预览图换成其它什么可以自动获取到的图。并非 Bug。

**Comment by drakeet** [comment]
之前的预览图，每一张都是我手动截图并上传我的服务器，这么做效率很低而且十分依赖我的时间，所以就停更了。

**Comment by hhaAndroid** [comment]
OK.明白了
