### ISSUE TITLE
求助大神，编译无法运行，报这个错误，环境：win10-64位、jdk8

### ISSUE THREAD

**Issue by xhAndroid** [drakeet/Meizhi#56]
Error:Execution failed for task ':app:compileRetrolambdaGooglePlayDebug'. > Could not resolve all dependencies for configuration ':app:retrolambdaConfig'. > Could not resolve net.orfjackal.retrolambda:retrolambda:2.3.0. Required by: Meizhi:app:unspecified > Could not resolve net.orfjackal.retrolambda:retrolambda:2.3.0. > Could not get resource 'https://repo1.maven.org/maven2/net/orfjackal/retrolambda/retrolambda/2.3.0/retrolambda-2.3.0.pom'. > Could not GET 'https://repo1.maven.org/maven2/net/orfjackal/retrolambda/retrolambda/2.3.0/retrolambda-2.3.0.pom'. > repo1.maven.org > Could not resolve net.orfjackal.retrolambda:retrolambda:2.3.0. > Could not get resource 'https://jcenter.bintray.com/net/orfjackal/retrolambda/retrolambda/2.3.0/retrolambda-2.3.0.pom'. > Could not GET 'https://jcenter.bintray.com/net/orfjackal/retrolambda/retrolambda/2.3.0/retrolambda-2.3.0.pom'. > jcenter.bintray.com > Could not resolve net.orfjackal.retrolambda:retrolambda:2.3.0. > Could not get resource 'https://oss.sonatype.org/content/repositories/snapshots/net/orfjackal/retrolambda/retrolambda/2.3.0/retrolambda-2.3.0.pom'. > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/net/orfjackal/retrolambda/retrolambda/2.3.0/retrolambda-2.3.0.pom'. > oss.sonatype.org

**Comment by drakeet** [comment]
请检查你的 maven 是否处于离线模式，检查网络是否能够正常连接。
