### ISSUE TITLE
代码中lambda的使用，可读性太差！！

### ISSUE THREAD

**Issue by George-Soros** [drakeet/Meizhi#58]

**Comment by drakeet** [comment]
Lambda 是更接近自然语言的语言，怎么能说可读性太差，那只能说你不懂或者不熟悉它。如果让一个不懂代码的人来看一个匿名内部类代码和一行 Lambda 代码，绝对是 Lambda 更直观，能容易让他理解。觉得难读，那是因为你的思维因为长期习惯使用匿名内部类或者程序思维，僵化了，请不要主观判断。

**Comment by George-Soros** [comment]
确实是Lambda不太熟悉。

**Comment by drakeet** [comment]
对于不熟悉 Lambda 或者思维被匿名内部类长期固化了的程序员来说，Lambda 却是会带来一定学习成本，但实际上熟悉它是很快很容易的过程，可以网上查询一下介绍很快就可以懂了，如果要更深入理解，推荐阅读《Java 8 函数式编程》这本书。

总之，Lambda 是趋势，Android 官方已经提供了新的编译构建工具 Jack 来兼容 Lambda 到 Java 8 以下了，日后也会越来越完善，越来越多人使用，学习和使用它应该是推荐的。
