### ISSUE TITLE
今天貌似不能从服务器拿数据了？

### ISSUE THREAD

**Issue by jutao** [drakeet/Meizhi#63]

**Comment by drakeet** [comment]
@daimajia

**Comment by sunshineliang** [comment]
我的也不能了

**Comment by daimajia** [comment]
@drakeet  @sunshineliang  咦？浏览器访问貌似没有什么问题

**Comment by drakeet** [comment]
感谢提醒，晚上我看看问题出在哪里。

**Comment by o0yangyang0o** [comment]
是的，我的也是无法获取到数据，能不能再界面上给个提示啊（比如：连接服务器失败），我还以为是自己手机的问题。。。

**Comment by drakeet** [comment]
@o0yangyang0o 可以的，今晚修复并加上连接失败提示。

**Comment by drakeet** [comment]
@jutao @o0yangyang0o @sunshineliang 
已修复，下载：http://fir.im/mengmeizhi
