### ISSUE TITLE
大兄弟，要更新app才行了

### ISSUE THREAD

**Issue by z-chu** [drakeet/Meizhi#65]
貌似 gank的API来大姨妈了，兄弟你快解决下，还指望用app看gank.io呢。
![webwxgetmsgimg](https://cloud.githubusercontent.com/assets/13902657/20826098/88326406-b8a3-11e6-8030-835de24af4f6.jpg)

**Comment by drakeet** [comment]
已修复，已更新，已更新代码，见#64
